data_dir_path: 'data/train/'
pkl_dump_file_name: 'data/training/dump.pkl'
image_size: 32
img_rows: 32
img_cols: 32
img_channels: 3
model_json_path: 'models/model.json'
model_weight_path: 'models/model.h5'
vocab_dir_base_name: './data/vocab/'
vocab_tagger: ' -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd'
